version: '3.8'

services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - ./db/.init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./db/data:/var/lib/mysql
    # development settings
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_LOCAL_PORT
    # production settings
    # expose:
    #   - $MYSQLDB_LOCAL_PORT
    networks:
      - private

  api:
    depends_on:
      - db
    build:
      context: ./api
    command: "npm start"
    restart: unless-stopped
    env_file: ./.env
    # development settings
    ports:
      - $NODE_API_LOCAL_PORT:$NODE_API_LOCAL_PORT
    # production settings
    # expose:
    #   - $NODE_API_LOCAL_PORT
    networks:
      - public
      - private
    environment:
      - DB_HOST=db
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_LOCAL_PORT
    stdin_open: true
    tty: true

  client:
    depends_on:
      - api
    build:
      context: ./client
    command: "npm start"
    restart: unless-stopped
    ports:
      - $NODE_CLIENT_LOCAL_PORT:$NODE_CLIENT_PUBLICK_PORT

networks:
  public:
  private:
