version: '3.9'
services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=/run/secrets/db-password
  backend:
    build:
      context: api
    command: npm start
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    expose:
      - 8000
    secrets:
      - .env
    depends_on:
      - db
    restart: always
  frontend:
    build:
      context: client
    restart: always
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - backend
secrets:
  db-password:
    file: db/.env

